language: go
go: stable

matrix:
  include:
    - os: windows

install:
  - set -e
  - |
    if [[ $TRAVIS_OS_NAME == windows ]]; then
      wget -O ~/bin/yasm.exe http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe
      mkdir ~/aom && cd ~/aom
      git clone --depth=1 https://aomedia.googlesource.com/aom
      mkdir build && cd build
      cmake ../aom -G 'MSYS Makefiles' \
        -DCMAKE_MAKE_PROGRAM=mingw32-make \
        -DCMAKE_C_COMPILER=gcc \
        -DCMAKE_CXX_COMPILER=g++ \
        -DCMAKE_INSTALL_PREFIX=~/aom/dist \
        -DCMAKE_BUILD_TYPE=Release \
        -DCONFIG_AV1_DECODER=0 \
        -DENABLE_DOCS=0 \
        -DENABLE_EXAMPLES=0 \
        -DENABLE_TOOLS=0 \
        -DENABLE_TESTS=0 \
        -DCONFIG_LOWBITDEPTH=1
      mingw32-make -j3
      mingw32-make install
      export CGO_CFLAGS="-IC:/Users/travis/aom/dist/include"
      export CGO_LDFLAGS="-static -LC:/Users/travis/aom/dist/lib"
    fi

script:
  - cd $TRAVIS_BUILD_DIR
  - go get -v ./...

notifications:
  email:
    on_success: never
