image: Visual Studio 2017
configuration: Release
clone_folder: C:\projects\go-avif\src\github.com\Kagami\go-avif

install:
  # Vars
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set PATH=%PATH%;C:\projects;C:\msys64\mingw64\bin
  - set GOPATH=C:\projects\go-avif
  - set "CGO_CFLAGS=-I../../../../../aom"
  - set "CGO_LDFLAGS=-static -L../../../../../aom_build/%CONFIGURATION%"
  # Tools
  - cd C:\projects
  - appveyor DownloadFile http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe -FileName yasm.exe
  # libaom
  - IF NOT EXIST aom git clone https://aomedia.googlesource.com/aom
  - cd aom && git pull && cd ..
  - mkdir -p aom_build && cd aom_build
  - cmake ../aom -G "Visual Studio 15 2017" -A x64 -DCONFIG_AV1_DECODER=0 -DENABLE_DOCS=0 -DENABLE_EXAMPLES=0 -DENABLE_TOOLS=0 -DENABLE_TESTS=0 -DCONFIG_LOWBITDEPTH=1
  - cmake --build . --config %CONFIGURATION%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - go get -v ./...

artifacts:
  - path: ..\..\..\..\bin\avif.exe
    name: $(APPVEYOR_PROJECT_NAME)

cache:
  - C:\projects\aom
  - C:\projects\aom_build
