image: Visual Studio 2017
clone_folder: C:\projects\go-avif\src\github.com\Kagami\go-avif

install:
  - set PATH=%PATH%;C:\msys64\mingw64\bin
  - set GOPATH=C:\projects\go-avif
  - set CGO_LDFLAGS=-static
  - C:\msys64\usr\bin\pacman --noconfirm -S mingw-w64-x86_64-cmake mingw-w64-x86_64-yasm
  - C:\msys64\usr\bin\bash -lc "cd /c/projects && git clone --depth=1 https://aomedia.googlesource.com/aom && mkdir aom_build && cd aom_build && cmake ../aom -G 'MSYS Makefiles' -DCMAKE_BUILD_TYPE=Release -DCONFIG_AV1_DECODER=0 -DENABLE_DOCS=0 -DENABLE_EXAMPLES=0 -DENABLE_TOOLS=0 -DENABLE_TESTS=0 -DCONFIG_LOWBITDEPTH=1 && make -j4 && make install"

build_script:
  - go get -v ./...

artifacts:
  - path: ..\..\..\..\bin\avif.exe
    name: $(APPVEYOR_PROJECT_NAME)
